[versions]
netty = "4.1.127.Final"
shadow = "9.3.0"
snakeyaml = "2.4"
javassist = "3.30.2-GA"
jline = "3.30.5"
terminal = "3.30.5"

[libraries]
netty = { module = "io.netty:netty-all", version.ref = "netty" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
javassist = { module = "org.javassist:javassist", version.ref = "javassist" }
jline = { module = "org.jline:jline", version.ref = "jline" }
terminal = { module = "org.jline:jline-terminal", version.ref = "terminal" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }